### ISSUE TITLE
Meeting minutes: Nov 19 2021

### ISSUE THREAD

**Issue by nickmao1994** [UBC-MDS/abalone_age_classification#10]
**Participants:** Kiran Phaterpekar, Lynn, Nick Lisheng Mao, Rakesh Pandey

**Meeting purpose:** go through works from everyone, minor updates to code and prepare for release.

**Agenda:**

Communicate on everyone's work and yield to do list after this meeting.
Improve README file, exclude unnecessary table
Check if everything is ready for final submission

**To do:**
Kiran Phaterpekar - Update eda and tell Rakesh after completion (optional)
Nick Lisheng Mao- Update eda code to include a relative path to load data and improve formatting, tell Rakesh after completion
Rakesh Pandey - Proofread the code and make submission and release before Sat ddl.

**Next meeting:**
No scheduled meeting for milestone 1. 

Scribe: Nick
Proof-reader: Rakesh

**Comment by nickmao1994** [comment]
I have updated a relative path to data loading in EDA. @veerupandey

**Comment by kphaterp** [comment]
Let me know once you're done formatting your code in the EDA @nickmao1994 . I will complete some additional EDA once you're finished

**Comment by nickmao1994** [comment]
> 

Sure, I have done the formatting too.
