### ISSUE TITLE
Missing EDA table from Project prososal README file

### ISSUE THREAD

**Issue by kphaterp** [UBC-MDS/abalone_age_classification#13]
Guidelines state that we should:

Discuss at least one exploratory data analysis (EDA) table and one exploratory data analysis figure you will create that makes sense for your research question, the data that you have, and the analysis you plan to do.

We have EDA figures in the README file, but we still need an EDA table

**Comment by nickmao1994** [comment]
I have updated the code and merged pull request

**Comment by nickmao1994** [comment]
I have added the table and updated the code.
