### ISSUE TITLE
Need to provide additional information to describe EDA plots/tables. 

### ISSUE THREAD

**Issue by kphaterp** [UBC-MDS/abalone_age_classification#18]
Additional text should be provided to describe EDA plots and tables. Headers for each section of EDA should also be included to make the EDA.ipynb file look more organized. We should also add another table showing the distribution of classes in both the training and test datasets

**Comment by lynnwbl** [comment]
I have made some changes to improve the EDA file:

- Add title and references
- Make axis labels human readable
- Fix old/young threshold (old: > 11 instead of 10)
- Use mark_circle with opacity instead of mark_point to make trending lines stand out

**Comment by nickmao1994** [comment]
Changes to the EDA file:

- Add a story line and detailed explanation to each plot.
- Reordered output to make it easier for audience to catch important information
- Some small improvements to plots
