### ISSUE TITLE
Need to revise README.md and insert EDA link

### ISSUE THREAD

**Issue by lynnwbl** [UBC-MDS/abalone_age_classification#19]
TODO:
- Revise the bullet points into full paragraphs
- Point to the EDA file in the README

**Comment by lynnwbl** [comment]
Revision guideline - the README file should include the following parts:
- introduction
- how to use data
- dependencies
- license
- citation

**Comment by lynnwbl** [comment]
**Changes made:**

- Revise the bullet points into full paragraphs
- Point to the EDA file in the README

**TODO:**

- Add dependencies section to README file

**Comment by nickmao1994** [comment]
I have uploaded dependencies file and add a section in README file.
