### ISSUE TITLE
Need to update README file trend line plot to the new one

### ISSUE THREAD

**Issue by kphaterp** [UBC-MDS/abalone_age_classification#23]
The updated trend line plot in the eda.ipynb file looks a little better, so we should update the README to include the updated plot

**Comment by lynnwbl** [comment]
Should we just remove the plots from README? We already have a link that points to the detailed EDA file.

**Comment by kphaterp** [comment]
@lynnwbl @veerupandey @nickmao1994  What does everyone think? It may look aesthetically better to just remove the plots since we have links for those plots already but I'm open to either decision

**Comment by nickmao1994** [comment]
I am fine with both options. I have seen some project to include basic eda in readme file.

**Comment by lynnwbl** [comment]
New plots have been added to README. Issue can be closed upon review.

**Comment by kphaterp** [comment]
Looks good to me
