### ISSUE TITLE
Preprocess X_test before fitting model or not?

### ISSUE THREAD

**Issue by lynnwbl** [UBC-MDS/abalone_age_classification#32]
I am currently working on the preprocessing script for milestone 2. 

One thing that I am not sure is that if we want to transform X_test even before we fit the classification model. As I learned in 571 and 573, in a general workflow usually we should only touch the test set until after we selected a final model, is that correct?
![image](https://user-images.githubusercontent.com/78331839/143303369-92eb4f8c-268a-4d89-b7d1-638ee570d4f6.png)

In Tiffany's example preprocessing script, she fit preprocessor on X_train and X_test in one script and output X_train_preprocessed and X_test_preprocessed into two seperate files, which is confusing to me. 

```
# scale test data using scale factor
  x_train <- training_data %>% 
    select(-class) 
  x_test <- test_data %>% 
    select(-class)
  pre_process_scaler <- preProcess(x_train, method = c("center", "scale"))
  x_train_scaled <- predict(pre_process_scaler, x_train)
  x_test_scaled <- predict(pre_process_scaler, x_test)
  training_scaled <- x_train_scaled %>% 
    mutate(class = training_data %>% select(class) %>% pull())
  test_scaled <- x_test_scaled %>% 
    mutate(class = test_data %>% select(class) %>% pull())
  
  # write scale factor to a file
  try({
    dir.create(out_dir)
  })
  saveRDS(pre_process_scaler, file = paste0(out_dir, "/scale_factor.rds"))
  
  # write training and test data to feather files
  write_feather(training_scaled, paste0(out_dir, "/training.feather"))
  write_feather(test_scaled, paste0(out_dir, "/test.feather"))
}
```
Link to Tiffany's script: https://github.com/ttimbers/breast_cancer_predictor/blob/9c19bd6ea34f76025218845db404bf13140b5c94/src/pre_process_wisc.r
Any ideas on how to approach this?

**Comment by lynnwbl** [comment]
I have added my script as pull request. Please review if it makes sense. Thanks.

**Comment by kphaterp** [comment]
I would think that we would only touch the test set after we've selected the model, since we're really only supposed to score the test set once

**Comment by veerupandey** [comment]
To my mind, it is acceptable to pre-process training and test data in this case, as pre-processing will not leak any information from test data to train data. While building the model we can read the processed train and test data directly.
