### ISSUE TITLE
Milestone 2 report: adding model interpretation

### ISSUE THREAD

**Issue by lynnwbl** [UBC-MDS/abalone_age_classification#55]
In addition to the EDA analysis and interpretations, can we also add some high-level interpretation to our final LR model (e.g. scores)?

**Comment by kphaterp** [comment]
Right, I forgot about this. I will include this shortly. Have we received scores on the test data?

**Comment by kphaterp** [comment]
Additionally, I need some help including the figure images properly with figure captions (should we use python?). I'm not entirely sure the most optimal way to do this. For now, I have just included the images via markdown without figure captions.
