### ISSUE TITLE
Reasoning for EDA literate document requires revision

### ISSUE THREAD

**Issue by kphaterp** [UBC-MDS/abalone_age_classification#72]
How does the unbalanced target variables influence your interpretation of EDA and potentially your results?

You have a lot of EDA results, which ones are effective in guiding you to address future steps in the project. Does it affect your hypothesis of the results from your task?

Feature variables are highly correlated, and what does that imply? Are there potentially lurking or redundant variables?

**Comment by nickmao1994** [comment]
Nick - deal with item three: Feature variables are highly correlated and one other issue why logistic regression is chosen.

**Comment by kphaterp** [comment]
Kiran - item 1: How does the unbalanced target variables influence your interpretation of EDA and potentially your results?
