### ISSUE TITLE
Meeting Minutes Dec 7th 10PM-11PM

### ISSUE THREAD

**Issue by lynnwbl** [UBC-MDS/abalone_age_classification#84]
- Docker file testing and finalizing
 - Auto build problem

- Milestone 2 TA feedbacks
  - "You have a lot of metrics here. What is the most important in your case and sums up the project?"
  - "Make sure your text in your figures aren't cut."
 
-  Improve and comment on 4 peer review

Scribe: Lynn
Proof-reader: Kiran

**Comment by lynnwbl** [comment]
Peer review link: 
https://github.com/UBC-MDS/data-analysis-review-2021/issues/13

**Comment by kphaterp** [comment]
Additional Comments from the TA:

Don't include files in your folders that don't mean anything. Everything in your folders will be evaluated.
The readability of your report is not clear on my end. I can't seem to grasp your major findings. Maybe try to sum up all your findings in a summary. It is relatively difficult to absorb what to take away from your findings.
Figure 5. Validation score with different hyperparameter C. Take this figure as an example. You would not see the quality of this image in a scientific report. I don't see how the captions are descriptive or conveying a narrative.
This is a summary grade for the whole quality of 3A and 3B.
"Your question, analysis and visualization should make sense. It doesn’t have to be complicated, but you should tell a story and have a narrative. Specifically, this should come through in your README and final report file." and "This should be an evolution of what was submitted at the proposal stage. " I might be incorrect but I did not see a visualization in your readme nor did I see a summary narrative of your results. Other groups have been able to bring a sufficient evolution from their previous milestone.
You should have a summary of your findings in a more organized manner. For maximum readability, avoid giving screenshots of tables, avoid computational variables, explain the most important findings in the tables. Summarize your findings in paragraphs that have topic sentences. The narrative should be clear to the reader. In many projects this has been demonstrated, but it's relatively not simple for your report.

**Comment by kphaterp** [comment]
I will fix figure captions (3) and address points 2 and 5 as well.
